server.port=8083
spring.application.name=email
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=irfananhar52@gmail.com
spring.mail.password=uvak dsfd uypm dgle
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true