server.port=8081
spring.application.name=demo
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5673}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:user}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:password}
spring.rabbitmq.connection-timeout=10000

rabbitmq.exchange=myExchange
rabbitmq.queue=myQueue
rabbitmq.routing-key=myRoutingKey

logging.level.com.irfan.demo=INFO
logging.level.org.springframework.amqp=DEBUG